# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='강사명')),
                ('birth', models.CharField(max_length=30, verbose_name='생년월일')),
                ('subject1', models.CharField(max_length=30, verbose_name='지도 과목 1')),
                ('subject2', models.CharField(blank=True, max_length=30, null=True, verbose_name='지도 과목 2')),
                ('postcode', models.CharField(max_length=10, verbose_name='우편번호')),
                ('addr1', models.CharField(max_length=200, verbose_name='주소')),
                ('addr2', models.CharField(max_length=200, verbose_name='상세주소')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('phone', models.CharField(max_length=30, verbose_name='전화번호')),
                ('portrait', models.ImageField(upload_to='portrait', verbose_name='증명사진')),
                ('document', models.FileField(upload_to='document', verbose_name='방과후학교 지도사 신청 서류')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='등록일자')),
            ],
        ),
    ]
