# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-16 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='수업명')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='수업분야')),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='document',
            field=models.FileField(help_text='위에서 양식을 다운로드 해주세요', upload_to='document', verbose_name='방과후학교 지도사 신청 서류'),
        ),
        migrations.AddField(
            model_name='subject',
            name='cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.SubjectCategory'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(to='teacher.Subject'),
        ),
    ]
