# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-16 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_auto_20180317_0626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('name',), 'verbose_name': '선생님', 'verbose_name_plural': '선생님 목록'},
        ),
        migrations.AlterField(
            model_name='subject',
            name='cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.SubjectCategory'),
        ),
    ]
