# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-18 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_auto_20180317_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject1',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject2',
        ),
    ]
