# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 23:07
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='체크 되어 있을 때 리스트에 표시 됩니다', verbose_name='표시여부')),
                ('title', models.CharField(max_length=40, verbose_name='포스트 제목')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='포스트 내용')),
                ('summery', models.TextField(verbose_name='요약 내용')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='업데이트')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '포스트',
                'verbose_name_plural': '포스트 목록',
            },
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='카테고리 코드')),
                ('name', models.CharField(max_length=40, verbose_name='카테고리 제목')),
                ('desc', models.CharField(max_length=80, verbose_name='카테고리 한줄 설명')),
                ('template', models.CharField(blank=True, default=None, help_text='이 카테고리가 특수한 템플릿을 쓸 경우 템플릿명', max_length=80, null=True, verbose_name='특수 템플릿')),
            ],
            options={
                'verbose_name': '포스트 카테고리',
                'verbose_name_plural': '포스트 카테고리 목록',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='cate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.PostCategory'),
        ),
    ]
