# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 23:07
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='페이지 제목')),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True, verbose_name='페이지 부제목(선택)')),
                ('featured', models.ImageField(blank=True, null=True, upload_to='featured', verbose_name='타이틀 이미지')),
                ('theme', models.CharField(blank=True, choices=[('', '밝게'), ('dark', '어둡게'), ('gray', '회색조'), ('custom', '커스텀')], default='', max_length=10, verbose_name='컬러 테마')),
                ('code', models.SlugField(unique=True, verbose_name='페이지 코드')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='페이지 내용')),
                ('style', models.TextField(blank=True, default='', null=True, verbose_name='Style')),
                ('script', models.TextField(blank=True, default='', null=True, verbose_name='Script')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='업데이트')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '페이지',
                'verbose_name_plural': '페이지 목록',
            },
        ),
    ]
