# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='제목')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='부제')),
                ('button_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='버튼명')),
                ('button_link', models.URLField(blank=True, null=True, verbose_name='버튼링크')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, editable=False)),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='slide', verbose_name='image')),
            ],
            options={
                'verbose_name': '슬라이드',
                'verbose_name_plural': '슬라이드 목록',
                'ordering': ['order'],
            },
        ),
    ]
