# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='학교명')),
                ('class_type', models.CharField(choices=[('direct', '직영'), ('outsourcing', '위탁')], max_length=20, verbose_name='강좌종류')),
                ('principal', models.CharField(blank=True, max_length=80, null=True, verbose_name='교장명')),
                ('assistant', models.CharField(blank=True, max_length=80, null=True, verbose_name='교감명')),
                ('after_manager', models.CharField(blank=True, max_length=80, null=True, verbose_name='방과후부장')),
                ('school_manager', models.CharField(blank=True, max_length=80, null=True, verbose_name='메니저')),
                ('note', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='주소')),
                ('phone', models.CharField(blank=True, max_length=80, null=True, verbose_name='전화번호')),
                ('students', models.IntegerField(default=0, verbose_name='전교생수')),
            ],
            options={
                'verbose_name': '학교',
                'verbose_name_plural': '학교 목록',
            },
        ),
        migrations.CreateModel(
            name='SchoolCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='분류명')),
            ],
            options={
                'verbose_name': '학교분류',
                'verbose_name_plural': '학교분류 목록',
            },
        ),
        migrations.CreateModel(
            name='SchoolDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='문서명')),
                ('file', models.FileField(upload_to='school_documents', verbose_name='문서')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.School', verbose_name='해당학교')),
            ],
            options={
                'verbose_name': '학교문서',
                'verbose_name_plural': '학교문서 목록',
            },
        ),
        migrations.AddField(
            model_name='school',
            name='cate',
            field=models.ManyToManyField(to='home.SchoolCategory', verbose_name='분류'),
        ),
    ]
