# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 00:07
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='weekday',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, '월'), (1, '화'), (2, '수'), (3, '목'), (4, '금'), (5, '토'), (6, '일')], max_length=7, verbose_name='개설요일'),
        ),
    ]
